name: .NET Framework Build and Publish Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
        
    - name: Locate MSBuild
      run: |
        $msbuildPath = where.exe msbuild
        Write-Host "MSBuild.exe is located at: $msbuildPath"
    
    - name: Restore NuGet packages
      run: |
        $msbuildPath = where.exe msbuild
        "& $msbuildPath" /t:restore EyeSaver.sln

    - name: Build with MSBuild
      run: |
        $msbuildPath = where.exe msbuild
        "& $msbuildPath" EyeSaver.sln /p:Configuration=Release /p:Platform="Any CPU" /m
    
    - name: Archive Release Artifacts
      run: |
        7z a EyeSaver.zip ./EyeSaver/bin/Release/*
        
    - name: Checkout Releases Repository
      uses: actions/checkout@v2
      with:
        repository: mdxz2048/EyeSaverReleases
        token: ${{ secrets.GITHUB_TOKEN }}
        path: releases

    - name: Copy files to the releases repository
      run: |
        Copy-Item EyeSaver.zip releases/

    - name: Commit and Push to Releases Repository
      run: |
        cd releases
        git config user.email "zhipeng2048@gmail.com"
        git config user.name "mdxz2048"
        git add .
        git commit -m "Release new version"
        git push
